### ISSUE TITLE
Song context menu is broken

### ISSUE THREAD

**Issue by nvirth** [StarGazer1258/BeatDrop#32] opened 2019-06-07 13:15 UTC
**Environment:**
Device - Oculus Rift S
OS - Edition: Windows 10 Education, Version: 1803, OS build: 17134.765
BeatDrop Version - 2.3.3

**Description of bug:**
Please see the attached video ([song-ctx-menu-issue.zip](https://github.com/StarGazer1258/BeatDrop/files/3266035/song-ctx-menu-issue.zip))
The song context menu, it looks like multiple songs' ctx menu opens at once, on top of each other. The topmost isn't the actually selected song at all.
Ctx menu items don't reagate to click

**Comment by StarGazer1258** [comment] 2019-06-07 13:21
Duplicate of #4. Guess it wasn’t fixed after all.

**Closed** 2019-06-07 13:22 UTC
Labels: duplicate
