### ISSUE TITLE
beatdrop is dead

### ISSUE THREAD

**Issue by darkerdark** [StarGazer1258/BeatDrop#141] opened 2020-01-09 12:58 UTC
impossible to download songs

**Comment by thomasfrobieter** [comment] 2020-01-09 18:22
https://www.reddit.com/r/beatsaber/comments/ekelja/beatdrop_wont_download_songs/

**Comment by StarGazer1258** [comment] 2020-01-09 21:40
Duplicate of #121. Further discussion will be tracked there.

**Closed by StarGazer1258** 2020-01-09 21:40 UTC
