### ISSUE TITLE
error downloading songs

### ISSUE THREAD

**Issue by BladesOni** [StarGazer1258/BeatDrop#147] opened 2020-01-11 15:01 UTC
Device -PC
OS - Windows 10
BeatDrop Version - 2.5.9

when trying to downloading songs from the beatdrop app it says "where was an error downloading the song with hash 2b2da842b687ec4cfbc948c583c21c79d4120de0 (it changes according to song). There may have been an error with BeatSaver's servers or the song may no longer be available. Please try again and contact the BeatSaver developers if problem persists.

1. Go to any download song menu
2. Click on any of the songs
3. click on dowload download

I expected the dong to download

it didn't download

![error1](https://user-images.githubusercontent.com/59742557/72206182-82f2ab80-3493-11ea-9c72-88f42c32f6f2.PNG)

![error2](https://user-images.githubusercontent.com/59742557/72206191-8dad4080-3493-11ea-9d90-2c718ccbf016.PNG)

**Comment by StarGazer1258** [comment] 2020-01-11 15:58
Duplicate of #121. Will merge fix #144 soon.

**Closed by StarGazer1258** 2020-01-11 15:58 UTC
Labels: duplicate
