### ISSUE TITLE
Whenever i try to download any song it keeps saying that there is a Hash error.

### ISSUE THREAD

**Issue by DavidWilliamGray** [StarGazer1258/BeatDrop#132] opened 2020-01-05 14:52 UTC
![hash error](https://user-images.githubusercontent.com/59534075/71781833-6c4fde80-2fd3-11ea-8714-21886e5f8b49.PNG)

**Comment by AlanoLeider** [comment] 2020-01-05 15:17
i got the seme error
![image](https://user-images.githubusercontent.com/30403463/71782113-58808a00-2f8b-11ea-8d7e-75c8bb56c3fe.png)

**Comment by jkreezan** [comment] 2020-01-05 21:59
I am having the same problem

**Comment by DavidWilliamGray** [comment] 2020-01-06 12:18
Im going to delete it and then redownload it and ill update you guys if it works

**Comment by DavidWilliamGray** [comment] 2020-01-06 12:20
Nope it did not work :(

**Comment by Snouckeur** [comment] 2020-01-06 17:36
Same issue on my WIN10 PC.
![image](https://user-images.githubusercontent.com/59575594/71836004-4d287e00-30b3-11ea-9a12-d41c1dad7390.png)

**Comment by hydroculator** [comment] 2020-01-06 21:30
Same here

**Comment by aoighost** [comment] 2020-01-07 01:44
same here

**Comment by mavericksv** [comment] 2020-01-07 03:36
I am also having this issue

**Comment by ratcom** [comment] 2020-01-07 13:52
same here too :(

**Comment by cherry25565** [comment] 2020-01-07 16:32
Same problem over here

**Comment by Spici23** [comment] 2020-01-07 23:26
I have the same problem someone have an idea how to fix

**Comment by shininghero** [comment] 2020-01-08 01:03
It appears to be a server issue on BeatSaver's part.  Their server instance is not properly handling the www subdomain.
API requests to beatsaver.com/* work fine, but requests to www.beatsaver.com/* give the below error:

    404 Site www.beatsaver.com is not served on this interface

**Comment by Hotrodkid96** [comment] 2020-01-08 03:18
same

**Comment by StarGazer1258** [comment] 2020-01-09 21:39
Duplicate of #121. Further discussion will be tracked there.

**Closed by StarGazer1258** 2020-01-09 21:39 UTC
