### ISSUE TITLE
Error/songs not available 

### ISSUE THREAD

**Issue by cinnapanda** [StarGazer1258/BeatDrop#137] opened 2020-01-07 20:49 UTC
Device: PC, Ryzen 5 1400
 
Error pops up reading song isn't available. Tried on about 20 more songs and same error has been popping up. Already tried to reinstall, go into AppRoaming and delete folder to reset the settings, and so far, nothing is resolving. 
![Screenshot (118)](https://user-images.githubusercontent.com/58573111/71928316-28341980-314c-11ea-9d87-319ef95076c9.png)

**Comment by shininghero** [comment] 2020-01-08 01:25
Looks like the BeatSaver service isn't handling the www subdomain correctly.  We should open an issue on their Github.
![image](https://user-images.githubusercontent.com/17071843/71942230-867fed00-318a-11ea-9da3-d18c61259fe2.png)

**Comment by cinnapanda** [comment] 2020-01-09 19:49
Thank you, it's actually my first time reporting, How do I go about it?

**Comment by StarGazer1258** [comment] 2020-01-09 21:40
Duplicate of #121. Further discussion will be tracked there.

**Closed by StarGazer1258** 2020-01-09 21:40 UTC
